"""
Django settings for GestionCamionesPepsi project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e@4j95k4u2*l3i8)uq*#e!6(a+@6c!74(nm06=g329h#!hkfy5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',  # Añadido para Content Security Policy
    'operaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Añadido para Content Security Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'operaciones.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'GestionCamionesPepsi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'operaciones' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestionCamionesPepsi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

#Archivos estáticos (CSS, JS, imágenes)
# Ruta base para acceder desde el navegador
STATIC_URL = '/static/'

#Ruta donde Django recopilará todos los archivos estáticos al ejecutar `collectstatic`
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Comentado para desarrollo

#Rutas adicionales donde buscar archivos estáticos durante el desarrollo
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#Archivos multimedia (si más adelante subes imágenes o documentos) 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#  Configuración de autenticación 
AUTH_USER_MODEL = 'operaciones.Usuario'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================
# Asegura que la cookie de sesión no sea accesible a través de JavaScript.
SESSION_COOKIE_HTTPONLY = True

# Asegura que la cookie CSRF no sea accesible a través de JavaScript.
CSRF_COOKIE_HTTPONLY = True

# Evita que el navegador "adivine" el tipo de contenido de un archivo, forzándolo a seguir el Content-Type.
SECURE_CONTENT_TYPE_NOSNIFF = True

# --- Content Security Policy (CSP) ---
# Formato para django-csp 4.0+
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'font-src': ("'self'", 'https://cdn.jsdelivr.net'),
        'script-src': ("'self'", 'https://cdn.jsdelivr.net', "'unsafe-inline'"),
        'style-src': ("'self'", 'https://cdn.jsdelivr.net', "'unsafe-inline'"),
    }
}
