# Generated by Django 5.2.6 on 2025-10-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('COORDINACION', 'Coordinación'), ('SUPERVISOR', 'Supervisor'), ('MECANICO', 'Mecánico'), ('CHOFER', 'Chofer'), ('GUARDIA', 'Guardia'), ('JEFE_TALLER', 'Jefe de Taller')], max_length=50),
        ),
    ]
