# Generated by Django 5.2.6 on 2025-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad del mecánico (ej: frenos, motor, electricidad, etc.)', max_length=100, null=True),
        ),
    ]
