# Generated by Django 5.2.6 on 2025-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_usuario_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General / Multiservicio'), ('MOTOR', 'Motor y transmisión'), ('ELECTRICIDAD', 'Electricidad automotriz'), ('FRENOS', 'Frenos y suspensión'), ('AIRE', 'Aire acondicionado y climatización'), ('CARROCERIA', 'Carrocería y pintura'), ('LLANTAS', 'Llantas y alineación'), ('DIAGNOSTICO', 'Diagnóstico computarizado')], help_text="Especialidad del mecánico (seleccione una opción o 'General').", max_length=50, null=True),
        ),
    ]
