# Generated by Django 5.2.6 on 2025-10-23 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_usuario_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_hora_llegada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de ingreso real al taller (registra Guardia)', null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='es_backup',
            field=models.BooleanField(default=False, help_text='Marcar si es un vehículo de respaldo.'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_actual',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_TALLER', 'En Taller'), ('EN_RUTA', 'En Ruta'), ('DE_BAJA', 'De Baja')], default='DISPONIBLE', max_length=50),
        ),
        migrations.CreateModel(
            name='Historial_Cambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('LOGIN', 'Inicio Sesión'), ('ACCESO', 'Acceso')], max_length=50)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100)),
                ('id_registro_afectado', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del cambio realizado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=50)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='operaciones.mantenimiento')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='operaciones.sitio'),
        ),
        migrations.CreateModel(
            name='Agenda_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atencion', models.CharField(choices=[('RUTINA', 'Revisión de Rutina'), ('EMERGENCIA', 'Emergencia'), ('MECANICA', 'Mecánica'), ('ELECTRICIDAD', 'Electricidad'), ('DOCUMENTACION', 'Documentación')], max_length=50)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_final', models.DateTimeField()),
                ('mantenimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='operaciones.mantenimiento')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='operaciones.taller')),
            ],
            options={
                'verbose_name': 'Bloque de Agenda',
                'verbose_name_plural': 'Agenda del Taller',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.taller'),
        ),
    ]
