# Generated by Django 5.2.6 on 2025-10-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_sitio_taller_remove_mantenimiento_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_taller',
            name='tipo_atencion',
            field=models.CharField(choices=[('RUTINA', 'Revisión de Rutina'), ('MECANICA', 'Mecánica'), ('ELECTRICIDAD', 'Electricidad'), ('DOCUMENTACION', 'Documentación')], max_length=50),
        ),
    ]
