# Generated by Django 5.2.6 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_agenda_taller_tipo_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_actual',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado (Pendiente Salida)'), ('DISPONIBLE', 'Disponible'), ('EN_TALLER', 'En Taller'), ('EN_RUTA', 'En Ruta'), ('DE_BAJA', 'De Baja')], default='DISPONIBLE', max_length=50),
        ),
    ]
