# Generated by Django 5.2.8 on 2025-11-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_agenda_taller_tipo_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_actual',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado (Pendiente Salida)'), ('DISPONIBLE', 'Disponible'), ('EN_TALLER', 'En Taller'), ('EN_RUTA', 'En Ruta'), ('DE_BAJA', 'De Baja')], default='DISPONIBLE', max_length=50),
        ),
        migrations.CreateModel(
            name='SolicitudBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=50)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_backup', to=settings.AUTH_USER_MODEL)),
                ('vehiculo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de Backup',
                'verbose_name_plural': 'Solicitudes de Backup',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
