# Generated by Django 5.2.8 on 2025-11-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_alter_vehiculo_estado_actual'),
        ('operaciones', '0007_alter_vehiculo_estado_actual_solicitudbackup'),
    ]

    operations = [
    ]
